### PR TITLE
Got it working on Parcel 1.11.x 🌅

### PR DESCRIPTION
**Pull request by c0deaddict**
After some digging around found the problem that caused #1 Apparently `JSAsset` is not part of the public API anymore. I ran the test and it works.

### CODE REVIEW

**Comment by ukoloff** [comment]
I reviewed your code and found it better than mine. In addition, I have almost forgotten about this plugin and have no plans on it.

I'd suppose you to take over `parcel-plugin-livescript`. Are you interested?

**Comment by c0deaddict** [comment]
Thanks for reviewing! Sure i'll take over the code. I'm planning on using the plugin for a large-ish project. How does taking over a repo work?

**Comment by ukoloff** [comment]
I think, you don't need to take over repo, just npm package.

1. You have to be registered @[npm](https://www.npmjs.com/). Tell me your login.

2. I [add](https://docs.npmjs.com/cli/owner) you to mantainers of [plugin](https://www.npmjs.com/package/parcel-plugin-livescript). Then you can publish new versions

3. You update package.json in [your repo](https://github.com/c0deaddict/parcel-plugin-livescript)
  - `version`++
  - `repository`, `bugs` and `homepage` to your repo
  - `author`

4. Merge your PR yourself (inside your repo)

5. Do whatever you want

6. You do `npm publish`

7. ...

8. PROFIT!

To tell the truth, I've never done this before, but I think it should thus work.

**Comment by c0deaddict** [comment]
Ok, that sounds logical, especially the profit :)

I've created a npm account under the same name as my github account: c0deaddict

**Comment by ukoloff** [comment]
I believe I granted you RW access to [npm package][admin]. Go ahead!

[admin]: https://www.npmjs.com/package/parcel-plugin-livescript/access

**Comment by c0deaddict** [comment]
Pushed version 1.1.0 to npm. Thanks!

**Pull request closed without merging**
